
package com.epam.brest.jmp.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebInterface", targetNamespace = "http://soap.jmp.brest.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.brest.jmp.soap.Task
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTask", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetTask")
    @ResponseWrapper(localName = "getTaskResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetTaskResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/getTaskRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/getTaskResponse")
    public Task getTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.brest.jmp.soap.Task
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTask", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.UpdateTask")
    @ResponseWrapper(localName = "updateTaskResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.UpdateTaskResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/updateTaskRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/updateTaskResponse")
    public Task updateTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Task arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.epam.brest.jmp.soap.Task>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gettAllTasksOfAUser", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GettAllTasksOfAUser")
    @ResponseWrapper(localName = "gettAllTasksOfAUserResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GettAllTasksOfAUserResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/gettAllTasksOfAUserRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/gettAllTasksOfAUserResponse")
    public List<Task> gettAllTasksOfAUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAllTasks", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteAllTasks")
    @ResponseWrapper(localName = "deleteAllTasksResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteAllTasksResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/deleteAllTasksRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/deleteAllTasksResponse")
    public Boolean deleteAllTasks();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.CreateUserResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/createUserRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/createUserResponse")
    public Integer createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.brest.jmp.soap.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetUserResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/getUserRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.brest.jmp.soap.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.UpdateUserResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/updateUserRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/updateUserResponse")
    public User updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteUserResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/deleteUserRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/deleteUserResponse")
    public Boolean deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.epam.brest.jmp.soap.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetAllUsersResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/getAllUsersRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/getAllUsersResponse")
    public List<User> getAllUsers();

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAllUsers", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteAllUsers")
    @ResponseWrapper(localName = "deleteAllUsersResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteAllUsersResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/deleteAllUsersRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/deleteAllUsersResponse")
    public Boolean deleteAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.brest.jmp.soap.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskOwner", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetTaskOwner")
    @ResponseWrapper(localName = "getTaskOwnerResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetTaskOwnerResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/getTaskOwnerRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/getTaskOwnerResponse")
    public User getTaskOwner(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.CreateTaskResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/createTaskRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/createTaskResponse")
    public Integer createTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Task arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.epam.brest.jmp.soap.Task>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTasks", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetAllTasks")
    @ResponseWrapper(localName = "getAllTasksResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.GetAllTasksResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/getAllTasksRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/getAllTasksResponse")
    public List<Task> getAllTasks();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTask", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteTask")
    @ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://soap.jmp.brest.epam.com/", className = "com.epam.brest.jmp.soap.DeleteTaskResponse")
    @Action(input = "http://soap.jmp.brest.epam.com/WebInterface/deleteTaskRequest", output = "http://soap.jmp.brest.epam.com/WebInterface/deleteTaskResponse")
    public Boolean deleteTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
